-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : dim. 10 avr. 2022 à 17:28
-- Version du serveur : 5.7.33
-- Version de PHP : 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `comparo_simple`
--

-- --------------------------------------------------------

--
-- Structure de la table `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `pseudo` varchar(25) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `admin`
--

INSERT INTO `admin` (`id`, `pseudo`, `password`) VALUES
(1, 'Peter', 'b7759fae5a2a7c94948e354bb46b63357c31d23e'),
(2, 'Usoland', 'b7759fae5a2a7c94948e354bb46b63357c31d23e'),
(3, 'Frankyland', 'b7759fae5a2a7c94948e354bb46b63357c31d23e');

-- --------------------------------------------------------

--
-- Structure de la table `destination`
--

CREATE TABLE `destination` (
  `id` int(11) NOT NULL,
  `location` varchar(255) NOT NULL,
  `price` int(11) NOT NULL,
  `image` text NOT NULL,
  `description` text NOT NULL,
  `adventure` int(11) NOT NULL,
  `food` int(11) NOT NULL,
  `rhum` int(11) NOT NULL,
  `earn_money` int(11) NOT NULL,
  `tour_operator_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `destination`
--

INSERT INTO `destination` (`id`, `location`, `price`, `image`, `description`, `adventure`, `food`, `rhum`, `earn_money`, `tour_operator_id`) VALUES
(1, 'Drum', 1650, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 2),
(2, 'Dressrosa', 1100, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 2),
(3, 'Wa-no-Kuni', 1390, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 1),
(4, 'Water-Seven', 2500, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 3),
(5, 'Amazon-Lily', 1000000000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 4),
(6, 'Kokoyashi', 2500, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 1),
(7, 'Ohara', 4500, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 2),
(8, 'Fushia', 3500, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 3),
(9, 'Saboady', 3500, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 1),
(10, 'Baratie', 3500, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 1),
(11, 'Weatheria', 40000, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 2),
(12, 'Weatheria', 35000, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 3),
(13, 'Drum', 1600, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 1),
(15, 'Amazon-Lily', 150000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 1),
(16, 'Amazon-Lily', 4500, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 2),
(17, 'Amazon-Lily', 5000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 3),
(18, 'Amazon-Lily', 2500, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 5),
(19, 'Amazon-Lily', 10000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 6),
(20, 'Amazon-Lily', 2500, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 7),
(21, 'Amazon-Lily', 12000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 8),
(22, 'Amazon-Lily', 3000, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 9),
(23, 'Amazon-Lily', 50, 'https://pm1.narvii.com/7310/188bffbd6283aefb030b1b12c2b7b2f2288af9ebr1-500-281v2_hq.jpg', 'Amazon Lily (アマゾン・リリー, Amazon Rirī), aussi nommée l\'île des femmes (女ヶ島, Nyōga shima), est une île habitée par la tribu Kuja. C\'est une île située dans Calm Belt. Grâce à cette mer où le vent et les tempêtes sont inexistantes et où les géants des mers (monstres marins) sont très nombreux, l\'île est très difficile d\'accès, voire impossible. Cette dernière est couverte d\'une immense forêt, le point central de l\'île étant une montagne munie d\'un profond cratère, sur laquelle est sculptée de gigantesques statues de serpent et le nom de la tribu indigène de l\'île, Kuja, gravé en Kanji. Dans le cratère de la montagne se trouve le village de la tribu Kuja. L\'architecture et le décor du village ressemble fortement à celle de la Chine féodale.', 5, 4, 1, 0, 10),
(24, 'Baratie', 2350, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 2),
(25, 'Baratie', 4320, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 3),
(26, 'Baratie', 4000, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 4),
(27, 'Baratie', 1930, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 5),
(28, 'Baratie', 5740, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 6),
(29, 'Baratie', 2100, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 7),
(30, 'Baratie', 2400, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 8),
(31, 'Baratie', 4270, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 9),
(32, 'Baratie', 50, 'https://i.pinimg.com/564x/13/f0/11/13f0119494dc0f1950b4947368bee68f.jpg', 'Le Baratie (バラティエ, Baratie) est un restaurant de haute mer, fondé et dirigé par Zeff. Il est situé dans la région de Sambas (サンバス 海域 Sanbasu Kaiiki) d\'East Blue. Le Baratie est un navire assez grand. Il a une forme ovale, avec des mâts normaux mais a un poisson comme figure de proue. Il y a des canons qui sont alignés sur les côtés, qui peuvent être utilisés pour le combat. Le Baratie dispose également de quatre niveaux : Pont Inférieur, où se trouve le restaurant principal. Middle Deck, qui est la cuisine principale. Pont Supérieur, où vingt-trois cuisiniers résident. Les Nageoires qui se déplient sur les côtés en dessous servent à stabiliser le restaurant pendant les intempéries et aussi, utilisés comme une plate-forme lors des batailles pour empêcher le restaurant lui-même de recevoir des dommages collatéraux.', 2, 5, 4, 2, 10),
(33, 'Dressrosa', 2450, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 1),
(34, 'Dressrosa', 2658, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 3),
(35, 'Dressrosa', 1999, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 4),
(36, 'Dressrosa', 1750, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 5),
(37, 'Dressrosa', 4850, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 6),
(38, 'Dressrosa', 6850, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 7),
(39, 'Dressrosa', 3620, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 8),
(40, 'Dressrosa', 8000, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 9),
(41, 'Dressrosa', 50, 'https://m.media-amazon.com/images/M/MV5BOTMyMjI1YTQtOThhNC00ODI2LWI5OTEtYWFiMGUzMTg5OWE4XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Dressrosa, décrit comme \"Le Pays de L\'Amour, de La Passion et des Jouets\" est un royaume situé dans le Nouveau Monde.\r\nDressrosa est une île luxueuse avec des palmiers, une piscine, un grand château du style anglais à l\'aspect d\'un manoir. L\'usine où sont produits les Smiles ainsi qu\'un Port de Commerce sont également présents sur cette île. L\'activité sombre de Dressrosa se déroule dans un énorme sous-sol sous le Palais Royal. En effet, c\'est en dessous du bâtiment que se situe La Maison des Jouets ainsi que Le Port de Commerce et l\'Usine de Smiles. Il existe un grand ascenseur reliant ses lieux au Palais. Il y aussi un Colisée appelé \"Le Colisée Corrida\" dirigé par Diamante, en dessous duquel se trouve l\'Usine de Smiles. Enfin, il y a une ville portuaire nommée Acacia où vivent humains et marionnettes vivantes (qui à la base étaient des humains).', 5, 4, 3, 1, 10),
(42, 'Wa-no-Kuni', 1650, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 2),
(43, 'Wa-no-Kuni', 1860, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 3),
(44, 'Wa-no-Kuni', 2100, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 4),
(45, 'Wa-no-Kuni', 1580, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 5),
(46, 'Wa-no-Kuni', 2560, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 6),
(47, 'Wa-no-Kuni', 15000, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 7),
(48, 'Wa-no-Kuni', 1899, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 8),
(49, 'Wa-no-Kuni', 1740, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 9),
(50, 'Wa-no-Kuni', 50, 'https://m.media-amazon.com/images/M/MV5BODkzMjE2ZmEtYzlmOS00ZTYzLWE5MjQtMTI4NTk3MDc3NWI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Le Pays des Wa (ワノ国, Wano Kuni), ou Wano, aussi appelé anciennement \"Pays de l\'Or\" est un pays peuplé essentiellement de samouraïs et de ninjas, non affilié au Gouvernement Mondial.\r\nL’île est située dans le Nouveau Monde. Autrefois dirigé par la Famille Kozuki, le pays est actuellement occupé par l\'Équipage de Kaido, allié au Shogun de l\'île, Kurozumi Orochi, et subit d\'ailleurs une grande répression depuis plus de 20 ans.\r\nLe pays se situe à proximité Calm Belt (plus du côté North Blue que de West Blue) d\'après le plan d\'Oden.', 5, 1, 1, 0, 10),
(51, 'Drum', 1700, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 3),
(52, 'Drum', 1750, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 4),
(53, 'Drum', 1800, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 5),
(54, 'Drum', 1850, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 6),
(55, 'Drum', 1900, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 7),
(56, 'Drum', 1950, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 8),
(57, 'Drum', 2000, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 9),
(58, 'Drum', 50, 'https://m.media-amazon.com/images/M/MV5BYzA1ZGY2MzItMzI4Ni00YjM3LThhNmEtNTE1NWRmMmVmMjhmXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_.jpg', 'L\'Île de Drum (ドラム島, Doramu-tō) est une île situé sur Grand Line. Cette île au climat polaire est recouverte de neige et dispose d\'une série de montagnes en forme de tambour connus comme Drum Rockies.', 2, 2, 3, 2, 10),
(59, 'Fushia', 1500, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 1),
(60, 'Fushia', 1850, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 2),
(61, 'Fushia', 3200, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 4),
(62, 'Fushia', 2400, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 5),
(63, 'Fushia', 2310, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 6),
(64, 'Fushia', 1699, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 7),
(65, 'Fushia', 2100, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 8);
INSERT INTO `destination` (`id`, `location`, `price`, `image`, `description`, `adventure`, `food`, `rhum`, `earn_money`, `tour_operator_id`) VALUES
(66, 'Fushia', 2003, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 9),
(67, 'Fushia', 50, 'https://2img.net/image.noelshack.com/fichiers/2014/47/1416754576-one-piece-background-036-by-lorenorkerstinxx-d7nclg8.jpg', 'Ce village est bordé par la mer au sud, les montagnes (dont le Mont Corvo) à l\'ouest et une plaine à l\'est. Plusieurs bandits des montagnes notables vivent dans ou autour de la montagne, près du village, causant le chaos occasionnellement pour les villageois ou aidant en fonction des besoins. La ville semble être plutôt inconnue, donc les habitants sont heureux et fiers que leur ville puisse devenir connue pour être le lieu de naissance d\'un pirate célèbre.\r\nDans la mer bordant le village, vit un monstre marin local nommée Monstre de la Baie.\r\nLe village est situé à proximité de la masse continentale supérieure proche de Red Line au nord-est de East Blue.', 4, 5, 5, 2, 10),
(68, 'Kokoyashi', 2700, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 2),
(69, 'Kokoyashi', 2450, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 3),
(70, 'Kokoyashi', 2589, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 4),
(71, 'Kokoyashi', 2999, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 6),
(72, 'Kokoyashi', 2145, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 5),
(73, 'Kokoyashi', 2600, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 7),
(74, 'Kokoyashi', 3650, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 8),
(75, 'Kokoyashi', 3000, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 9),
(76, 'Kokoyashi', 50, 'https://i.servimg.com/u/f19/15/08/91/65/kokoya10.jpg', 'Le Village de Kokoyashi est le lieu le plus proche d\'Arlong Park et c\'est ici qu\'Arlong avait choisi d\'exercer principalement sa tyrannie. Après la défaite d\'Arlong, le village retrouva sa tranquillité.\r\nLe verger de mandariniers est une attraction locale pour les amoureux de ce fruit. Vous pouvez cuisiner  et parfois cultiver les mandarines dont raffole la population.', 2, 5, 4, 5, 10),
(77, 'Ohara', 4000, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 1),
(78, 'Ohara', 4100, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 3),
(79, 'Ohara', 4399, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 4),
(80, 'Ohara', 4750, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 5),
(81, 'Ohara', 4633, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 6),
(82, 'Ohara', 4872, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 7),
(83, 'Ohara', 4358, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 8),
(84, 'Ohara', 5000, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 9),
(85, 'Ohara', 50, 'https://pm1.narvii.com/7096/1b038d5a724933a82df1a00f3646a0e6d085b39ar1-1600-911v2_hq.jpg', 'Ohara est une île située dans West Blue. Au centre de l’île se trouve un grand arbre nommé l\'arbre de la Cognition dont l\'intérieur est creux, contenant la célèbre bibliothèque d\'Ohara. L\'île se compose principalement d\'archéologues.', 2, 0, 0, 0, 10),
(86, 'Saboady', 4050, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 2),
(87, 'Saboady', 4300, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 3),
(88, 'Saboady', 3210, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 4),
(89, 'Saboady', 4759, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 5),
(90, 'Saboady', 4820, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 6),
(91, 'Saboady', 3400, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 7),
(92, 'Saboady', 4765, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 8),
(93, 'Saboady', 5599, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 9),
(94, 'Saboady', 50, 'https://i.servimg.com/u/f47/13/67/64/62/tm/archip10.png', 'L\'Archipel des Sabaody se trouve sur la première moitié de Grand Line et est une zone proche de Red Line. Bien que le lieu soit appelé archipel, c\'est en fait un réseau de mangroves formant une forêt massive au milieu de l\'océan. Chaque mangrove prend racine au fond de l\'océan et chaque arbre de la forêt forme un \"îlot\". Cet îlot se forme sur les racines de la mangrove ce qui permet aux personnes d\'y vivre. Les îlots sont reliés entre eux ce qui va ainsi former \"l\'archipel\" de mangroves.', 5, 2, 2, 0, 10),
(95, 'Water-Seven', 1450, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 1),
(96, 'Water-Seven', 1460, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 2),
(97, 'Water-Seven', 1680, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 4),
(98, 'Water-Seven', 1390, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 5),
(99, 'Water-Seven', 1269, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 6),
(100, 'Water-Seven', 1799, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 7),
(101, 'Water-Seven', 1285, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 8),
(102, 'Water-Seven', 1970, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 9),
(103, 'Water-Seven', 50, 'https://2img.net/h/img110.xooimage.com/files/b/d/6/1-4fe6718.jpg', 'Water 7 (水の都ウォーターセブン, Mizu no Miyako Wōtā Sebun) est une ville connue pour ses charpentiers marins aux talents exceptionnels pour la construction de navire en tout genre.\r\nWater Seven a sept \"Docks\", c\'est à dire sept quais possédant les charpentiers les plus expérimentés.\r\nCette ville est connue aussi pour avoir abrité Tom, le charpentier du bateau du légendaire Gol D. Roger, l\'Oro Jackson. En ville,  il y a des canaux qui sillonnent la ville et qui vont de toits en toits et les masques portés par certains habitants ressemblent beaucoup à des masques vénitiens.', 4, 5, 5, 5, 10),
(104, 'Weatheria', 14000, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 1),
(105, 'Weatheria', 20000, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 4),
(106, 'Weatheria', 25800, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 5),
(107, 'Weatheria', 26599, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 6),
(108, 'Weatheria', 34750, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 7),
(109, 'Weatheria', 23700, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 8),
(110, 'Weatheria', 45000, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 9),
(111, 'Weatheria', 50, 'https://i.pinimg.com/564x/12/ce/2f/12ce2f9450878be4ec74315c354ee0a7.jpg', 'Weatheria (ウェザリア, Wezaria) est un îlot Céleste artificiel spécialisé dans l\'étude des climats et de l\'atmosphère mais aussi sur la géographie du monde.\r\nCet îlot se déplace à travers le monde entier et récolte beaucoup d\'informations sur la météorologie. Les habitants de Weatheria sont tous très vieux et sont des experts dans la matière de la météo. Ils ont même inventé un système de bulle pouvant contenir des nuages de pluie, de foudre... Ce sont les weatherballs.', 1, 3, 1, 5, 10),
(113, 'Gyojin-tō', 25000, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 1),
(114, 'Gyojin-tō', 24999, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 2),
(115, 'Gyojin-tō', 26700, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 3),
(116, 'Gyojin-tō', 25800, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 4),
(117, 'Gyojin-tō', 27900, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 5),
(118, 'Gyojin-tō', 27000, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 6),
(119, 'Gyojin-tō', 25600, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 7),
(120, 'Gyojin-tō', 24500, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 8),
(121, 'Gyojin-tō', 29000, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 9),
(122, 'Gyojin-tō', 50, 'https://pm1.narvii.com/7508/d7f04cefea72609053da59c82979ed67e2a429b7r4-600-300_00.jpg', 'L\'île des Hommes-Poissons est la terre natale des Sirènes et des Hommes-Poissons. Contrairement à d\'autres îles, il s\'agit là d\'une île sous-marine qui se situe à 10 000 mètres de profondeur en-dessous de Red Line. ', 5, 5, 5, 4, 10);

-- --------------------------------------------------------

--
-- Structure de la table `review`
--

CREATE TABLE `review` (
  `id` int(11) NOT NULL,
  `message` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `tour_operator_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `review`
--

INSERT INTO `review` (`id`, `message`, `author`, `tour_operator_id`) VALUES
(1, 'Super voyage, prestation au top !!', 'Dylan', 2),
(2, 'Tout est inclus dans le prix, c\'est cool, je recommande', 'Xavier', 3),
(3, 'Un peu cher, mais ça vaut le coup', 'Marc', 2),
(4, 'arnaque!!!! a fuire!!!', 'Mathis', 2),
(5, 'Kiiiiing BOOOOOOB !', 'Bob', 3),
(6, 'Je surveille mes eleves', 'Nicolas', 2),
(14, 'C\'est pas excessif pour du all inclusive !!!', 'Romain', 4),
(15, 'J\'ai connu mieux...', 'Hugo', 2),
(16, 'Passable', 'Adrien', 4),
(17, 'Au top, je repartirais en voyage avec cette agence :)', 'Prince-sama', 1),
(18, 'Super !', 'Hamza', 10),
(19, 'Super Expérience !!!', 'Marie-Laure', 10),
(20, 'L’agence est limite !!\r\nLa conseillère un peu perdu ...\r\nSur place : les deux pilotes-vacances sont rarement présente donc obliger de leur courir après tout le long de la journée !!', 'Benji', 9),
(21, 'Agence à éviter...\r\nCela fait 15 jours que j essaie de réserver un séjour combiné  (qui apparait sur le site) au prix très intéressant... comme par hasard je ne peux jamais finaliser...et comme par hasard je ne peux jamais avoir un interlocuteur par téléphone\r\nAgence à rayer !!!', 'Riad', 8),
(22, 'Service client irréprochable et contact chaleureux.\r\n', 'Frederic', 8),
(23, 'Très bon accueil, de précieux conseils.', 'Sarah', 7),
(24, 'Agence efficace\r\n', 'Axel', 6),
(25, 'Très bon accueil Je suis passée à l’agence la semaine dernière, on  a su parfaitement répondre à toutes mes questions. Je recommande.', 'Merry', 5);

-- --------------------------------------------------------

--
-- Structure de la table `tour_operator`
--

CREATE TABLE `tour_operator` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `link` text NOT NULL,
  `grade_count` int(11) NOT NULL DEFAULT '0',
  `grade_total` int(11) NOT NULL DEFAULT '0',
  `is_premium` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `tour_operator`
--

INSERT INTO `tour_operator` (`id`, `name`, `link`, `grade_count`, `grade_total`, `is_premium`) VALUES
(1, 'Salaun Holidays', 'https://www.salaun-holidays.com/', 1, 5, 0),
(2, 'Fram', 'https://www.fram.fr/', 4, 4, 1),
(3, 'Heliades', 'https://www.heliades.fr/', 1, 4, 0),
(4, 'Go Voyage', 'https://www.govoyages.com/', 1, 2, 1),
(5, 'Promovacances', 'https://www.promovacances.com/', 1, 5, 0),
(6, 'Travelling Post', 'https://www.comptoirdesvoyages.fr/', 1, 3, 0),
(7, 'Havas', 'https://www.havas-voyages.fr/', 1, 4, 1),
(8, 'Selectour', 'https://www.selectour.com/', 2, 4, 0),
(9, 'TUI', 'https://www.tui.fr/', 1, 1, 1),
(10, 'Going Merry', 'https://www.kuoni.fr/', 2, 9, 1);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `destination`
--
ALTER TABLE `destination`
  ADD PRIMARY KEY (`id`),
  ADD KEY `destination_tour_operator` (`tour_operator_id`);

--
-- Index pour la table `review`
--
ALTER TABLE `review`
  ADD PRIMARY KEY (`id`),
  ADD KEY `review_tour_operator` (`tour_operator_id`);

--
-- Index pour la table `tour_operator`
--
ALTER TABLE `tour_operator`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT pour la table `destination`
--
ALTER TABLE `destination`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=133;

--
-- AUTO_INCREMENT pour la table `review`
--
ALTER TABLE `review`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT pour la table `tour_operator`
--
ALTER TABLE `tour_operator`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `destination`
--
ALTER TABLE `destination`
  ADD CONSTRAINT `destination_tour_operator` FOREIGN KEY (`tour_operator_id`) REFERENCES `tour_operator` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Contraintes pour la table `review`
--
ALTER TABLE `review`
  ADD CONSTRAINT `review_tour_operator` FOREIGN KEY (`tour_operator_id`) REFERENCES `tour_operator` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
